export * from './acceptanceHistory.service';
import { AcceptanceHistoryService } from './acceptanceHistory.service';
export * from './account.service';
import { AccountService } from './account.service';
export * from './address.service';
import { AddressService } from './address.service';
export * from './affiliate.service';
import { AffiliateService } from './affiliate.service';
export * from './affiliateCommission.service';
import { AffiliateCommissionService } from './affiliateCommission.service';
export * from './answers.service';
import { AnswersService } from './answers.service';
export * from './bGV.service';
import { BGVService } from './bGV.service';
export * from './bulkExcelMapping.service';
import { BulkExcelMappingService } from './bulkExcelMapping.service';
export * from './callAttempt.service';
import { CallAttemptService } from './callAttempt.service';
export * from './candidateScore.service';
import { CandidateScoreService } from './candidateScore.service';
export * from './complianceDocument.service';
import { ComplianceDocumentService } from './complianceDocument.service';
export * from './consent.service';
import { ConsentService } from './consent.service';
export * from './contact.service';
import { ContactService } from './contact.service';
export * from './contractorFreelancer.service';
import { ContractorFreelancerService } from './contractorFreelancer.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './demo.service';
import { DemoService } from './demo.service';
export * from './designation.service';
import { DesignationService } from './designation.service';
export * from './dropDown.service';
import { DropDownService } from './dropDown.service';
export * from './emailAccount.service';
import { EmailAccountService } from './emailAccount.service';
export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './excelMapping.service';
import { ExcelMappingService } from './excelMapping.service';
export * from './feedback.service';
import { FeedbackService } from './feedback.service';
export * from './finalResponse.service';
import { FinalResponseService } from './finalResponse.service';
export * from './follower.service';
import { FollowerService } from './follower.service';
export * from './freelance.service';
import { FreelanceService } from './freelance.service';
export * from './futureCustomer.service';
import { FutureCustomerService } from './futureCustomer.service';
export * from './interview.service';
import { InterviewService } from './interview.service';
export * from './interviewSchedulesRange.service';
import { InterviewSchedulesRangeService } from './interviewSchedulesRange.service';
export * from './job.service';
import { JobService } from './job.service';
export * from './languages.service';
import { LanguagesService } from './languages.service';
export * from './media.service';
import { MediaService } from './media.service';
export * from './openAPI.service';
import { OpenAPIService } from './openAPI.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './otp.service';
import { OtpService } from './otp.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './pushNotification.service';
import { PushNotificationService } from './pushNotification.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './recruiter.service';
import { RecruiterService } from './recruiter.service';
export * from './recruiterContractor.service';
import { RecruiterContractorService } from './recruiterContractor.service';
export * from './retakeInterview.service';
import { RetakeInterviewService } from './retakeInterview.service';
export * from './setting.service';
import { SettingService } from './setting.service';
export * from './shoppingCart.service';
import { ShoppingCartService } from './shoppingCart.service';
export * from './skill.service';
import { SkillService } from './skill.service';
export * from './subAdmin.service';
import { SubAdminService } from './subAdmin.service';
export * from './supportAdmin.service';
import { SupportAdminService } from './supportAdmin.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './uploadDriveLink.service';
import { UploadDriveLinkService } from './uploadDriveLink.service';
export * from './userPerformance.service';
import { UserPerformanceService } from './userPerformance.service';
export const APIS = [AcceptanceHistoryService, AccountService, AddressService, AffiliateService, AffiliateCommissionService, AnswersService, BGVService, BulkExcelMappingService, CallAttemptService, CandidateScoreService, ComplianceDocumentService, ConsentService, ContactService, ContractorFreelancerService, CustomerService, DemoService, DesignationService, DropDownService, EmailAccountService, EmployeeService, ExcelMappingService, FeedbackService, FinalResponseService, FollowerService, FreelanceService, FutureCustomerService, InterviewService, InterviewSchedulesRangeService, JobService, LanguagesService, MediaService, OpenAPIService, OrderService, OtpService, PaymentService, ProductService, PushNotificationService, QuestionService, RecruiterService, RecruiterContractorService, RetakeInterviewService, SettingService, ShoppingCartService, SkillService, SubAdminService, SupportAdminService, TagsService, UploadDriveLinkService, UserPerformanceService];
