IF DB_ID('SuperAdminBlockDB') IS NULL
BEGIN
  CREATE DATABASE SuperAdminBlockDB;
END
GO

USE SuperAdminBlockDB;
GO

IF OBJECT_ID('dbo.Orders', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Orders (
    Id NVARCHAR(50) NOT NULL PRIMARY KEY,
    Customer NVARCHAR(150) NOT NULL,
    Status NVARCHAR(60) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

IF OBJECT_ID('dbo.Credits', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Credits (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerId NVARCHAR(60) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    ActionType NVARCHAR(30) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

IF OBJECT_ID('dbo.Customers', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Customers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Email NVARCHAR(120) NOT NULL,
    Company NVARCHAR(120) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

IF OBJECT_ID('dbo.InterviewSchedules', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.InterviewSchedules (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Candidate NVARCHAR(120) NOT NULL,
    Role NVARCHAR(120) NOT NULL,
    SlotTime NVARCHAR(50) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO

IF OBJECT_ID('dbo.ContractRequests', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ContractRequests (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Company NVARCHAR(120) NOT NULL,
    ContractType NVARCHAR(120) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
GO
