/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AboutCompanyJob } from './aboutCompanyJob';


export interface AboutCompanySchema { 
    aboutCompanyJob?: AboutCompanyJob;
    isSuccess?: boolean;
    message?: string | null;
}

