/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcceptanceHistory { 
    id?: number;
    userId?: number;
    complianceDocumentVersionId?: number;
    name?: string | null;
    type?: string | null;
    documentVersion?: string | null;
    htmlCode?: string | null;
    isAccepted?: boolean;
    acceptedOn?: string;
    ipSignature?: string | null;
    deviceInfo?: string | null;
    locationInfo?: string | null;
    documentContentHash?: string | null;
}

