/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';


export interface AddressDtoSchema { 
    addressDto?: AddressDto;
    isSuccess?: boolean;
    message?: string | null;
}

