/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AffiliatePerformance } from './affiliatePerformance';


export interface AffiliatePerformanceSchema { 
    affiliatePerformance?: AffiliatePerformance;
    isSuccess?: boolean;
    message?: string | null;
}

