/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AffiliateTransactions } from './affiliateTransactions';


export interface AffiliateTransactionsSchema { 
    affiliateTransactions?: AffiliateTransactions;
    isSuccess?: boolean;
    message?: string | null;
}

