/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AffiliateEarnings } from './affiliateEarnings';


export interface AffiliateEarningsSchema { 
    affiliateEarnings?: AffiliateEarnings;
    isSuccess?: boolean;
    message?: string | null;
}

