/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Affiliate } from './affiliate';


export interface AffiliateListSchema { 
    affiliateList?: Array<Affiliate> | null;
    isSuccess?: boolean;
    message?: string | null;
}

