/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AffiliateEarnings { 
    id?: number;
    title?: string | null;
    earningType?: string | null;
    conversion?: number;
    createdAt?: string;
    userId?: number;
    jobId?: number;
    isSuccess?: boolean;
}

