/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AllSettingSchema { 
    name?: string | null;
    isSuccess?: boolean;
    message?: string | null;
}

