/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AnswersDto { 
    id?: number;
    userId?: number;
    interviewId?: number;
    questionId?: number;
    answerText?: string | null;
    answerVideoPath?: string | null;
    score?: number;
    accessLevel?: string | null;
    isDeleted?: boolean;
    isEducative?: boolean;
    isItWorthy?: boolean;
    answerType?: number;
    videoUrl?: string | null;
    videoduration?: string | null;
    isInterviewQuestion?: boolean;
    isVideo?: boolean;
}

