/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplyJobDto { 
    id?: number;
    userId?: number;
    jobId?: number;
    appliedAt?: string;
    applicationStatus?: string | null;
}

