/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookDemo { 
    id?: number;
    recruiterId?: number;
    companyName?: string | null;
    name?: string | null;
    officeEmail?: string | null;
    guestEmail?: string | null;
    mobileNumber?: string | null;
    description?: string | null;
}

