/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkExcelMappingsDto } from './bulkExcelMappingsDto';


export interface BulkExcelMappingListSchema { 
    bulkExcelMappingsDto?: Array<BulkExcelMappingsDto> | null;
    isSuccess?: boolean;
    message?: string | null;
}

