/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CallAttemptDto { 
    id?: number;
    adminId?: number;
    candidateId?: number;
    callAttemptCount?: number;
    callAttemptResponse?: string | null;
    attemptedAt?: string;
    companyId?: number;
    orderId?: number;
    callBackOnTime?: string;
}

