/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallAttemptDto } from './callAttemptDto';


export interface CallAttemptSchema { 
    callAttemptDto?: CallAttemptDto;
    isSuccess?: boolean;
    message?: string | null;
}

