/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tags } from './tags';


export interface CandidateList { 
    id?: number;
    name?: string | null;
    userName?: string | null;
    description?: string | null;
    image?: string | null;
    companyName?: string | null;
    exprience?: string | null;
    noticePeriod?: string | null;
    salary?: string | null;
    expectedSalary?: string | null;
    tags?: Array<Tags> | null;
    createdOn?: string;
    isSaved?: boolean;
    role?: string | null;
    rank?: number;
    isPremiumResume?: boolean;
    location?: string | null;
    isPremium?: boolean;
    score?: number;
    jobTitle?: string | null;
    qualification?: string | null;
    resumeId?: number;
    resumePath?: string | null;
    resumeName?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    isVideoEmpty?: boolean;
    isSalaryConfidential?: boolean;
    years?: number;
    isPurchased?: boolean;
    isInterviewCompleted?: boolean;
    interviewStatus?: string | null;
    isInterviewScheduled?: boolean;
    isPrivate?: boolean;
    isPrimeRecruiter?: boolean;
    isTopCandidate?: boolean;
    isPrimeCandidate?: boolean;
    isVerified?: boolean;
    isPrivateInterviewSchedule?: boolean;
    course?: string | null;
    specialization?: string | null;
}

