/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationCandidateList } from './paginationCandidateList';


export interface CandidateListResponse { 
    candidateListResponses?: PaginationCandidateList;
    isSuccess?: boolean;
    message?: string | null;
}

