/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CareerPreferencesResponse { 
    id?: number;
    userId?: number;
    preferredRole?: string | null;
    preferredCity?: string | null;
    expectedAnnualSalary?: string | null;
    jobType?: string | null;
    employmentType?: string | null;
    prefferedShift?: string | null;
    industrialType?: string | null;
    preferredWorkPlaceType?: string | null;
}

