/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoursesCertificationsDto } from './coursesCertificationsDto';


export interface CertificationsSchemaList { 
    courses_CertificationsDto?: Array<CoursesCertificationsDto> | null;
    isSuccess?: boolean;
    message?: string | null;
}

