/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderTotalsModelDto } from './orderTotalsModelDto';
import { ShoppingCartModelDto } from './shoppingCartModelDto';


export interface CheckoutConfirmModelDto { 
    warnings?: Array<string> | null;
    id?: number;
    redirectToMethod?: string | null;
    isSuccess?: boolean;
    message?: string | null;
    shoppingCart?: ShoppingCartModelDto;
    orderTotals?: OrderTotalsModelDto;
    isCreditsEnabled?: boolean;
}

