/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDto } from './commentDto';


export interface CommentDtoSchema { 
    commentDto?: CommentDto;
    isSuccess?: boolean;
    message?: string | null;
}

