/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentsResponse } from './commentsResponse';


export interface CommentsResponseReplyListSchema { 
    parentComment?: CommentsResponse;
    commentDto?: Array<CommentsResponse> | null;
    isSuccess?: boolean;
    message?: string | null;
}

