/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterestComments } from './interestComments';
import { InterestCommentsChild } from './interestCommentsChild';


export interface CommentList { 
    parentComment?: InterestComments;
    childComment?: Array<InterestCommentsChild> | null;
}

