/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Comments { 
    id?: number;
    message?: string | null;
    customerId?: number;
    parentCommentId?: number;
    actionId?: number;
    recruiterId?: number;
    commentTypeId?: number;
    commentType?: number;
    createdAt?: string;
    isEdited?: boolean;
}

