/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplianceDocumentVersionDto } from './complianceDocumentVersionDto';


export interface ComplianceDocumentVersionSchema { 
    complianceDocumentVersionDto?: ComplianceDocumentVersionDto;
    isSuccess?: boolean;
    message?: string | null;
}

