/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsentDto { 
    id?: number;
    userId?: number;
    consentType?: string | null;
    consentVersion?: string | null;
    isGranted?: boolean;
    timestamp?: string;
    ipAddress?: string | null;
    deviceInfo?: string | null;
    revokedDate?: string | null;
    createdAt?: string;
    updatedAt?: string;
    consentActionId?: number;
    acceptanceHistoryId?: number;
}

