/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentDto } from './consentDto';


export interface ConsentSchema { 
    consentDto?: ConsentDto;
    isSuccess?: boolean;
    message?: string | null;
}

