/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractDesignationCard } from './contractDesignationCard';
import { ContractJobCard } from './contractJobCard';


export interface ContractJobDescription { 
    contractJobCard?: ContractJobCard;
    contractDesignationCards?: Array<ContractDesignationCard> | null;
    isSuccess?: boolean;
    message?: string | null;
}

