/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSheetApprovalList } from './timeSheetApprovalList';


export interface ContractorCommittedJobDescription { 
    jobId?: number;
    projectName?: string | null;
    projectDuration?: string | null;
    totalRoles?: number;
    totalContractors?: number;
    designation?: string | null;
    timesheetPendingCount?: number;
    startedAt?: string;
    timeSheetApprovalLists?: Array<TimeSheetApprovalList> | null;
    isSuccess?: boolean;
    message?: string | null;
}

