/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContractFreelancerTimeSheetDto { 
    id?: number;
    contractJobId?: number;
    selectedWorkDate?: string;
    profileName?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    taskTitle?: string | null;
    taskSummary?: string | null;
    status?: string | null;
    hours?: string | null;
    declinedReason?: string | null;
    createdAt?: string;
}

