/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractDesignation } from './contractDesignation';


export interface ContractDesignationSchema { 
    contractDesignation?: ContractDesignation;
    isSuccess?: boolean;
    message?: string | null;
}

