/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { ContractCandidates } from './contractCandidates';


export interface ContractCandidatesPaginationSchema { 
    pagination?: Pagination;
    contractCandidates?: Array<ContractCandidates> | null;
    isSuccess?: boolean;
    message?: string | null;
}

