/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractFreelancerTimeSheetDto } from './contractFreelancerTimeSheetDto';


export interface ContractFreelancerTimeSheetListSchema { 
    contractFreelancerTimeSheetDtos?: Array<ContractFreelancerTimeSheetDto> | null;
    isSuccess?: boolean;
    message?: string | null;
}

