/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactFrom { 
    id?: number;
    userId?: number;
    name?: string | null;
    emailID?: string | null;
    phoneNumber?: string | null;
    type?: string | null;
    message?: string | null;
    address?: string | null;
    createdOn?: string;
}

