/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewSchedule } from './interviewSchedule';


export interface CreateInterviewScheduleRequest { 
    interviewSchedule?: InterviewSchedule;
    skills?: Array<string> | null;
}

