/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerInfoModelDto } from './customerInfoModelDto';


export interface CustomerInfoModelDtoSchema { 
    customerInfoModelDto?: CustomerInfoModelDto;
    isSuccess?: boolean;
    message?: string | null;
}

