/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tags } from './tags';


export interface CustomerBasicInfo { 
    userId?: number;
    customerName?: string | null;
    customerProfile?: string | null;
    workingCompanyName?: string | null;
    jobTitle?: string | null;
    workExperience?: string | null;
    currentAnnualSalary?: string | null;
    score?: number;
    skills?: Array<Tags> | null;
    companyName?: string | null;
    companyProfile?: string | null;
    followersCount?: number;
    isRecruiter?: boolean;
    jobSearchStatus?: string | null;
    userName?: string | null;
    course?: string | null;
    specialization?: string | null;
    isTopCandidate?: boolean;
    isPrimeRecruiter?: boolean;
    isVerified?: boolean;
    isPrimeCandidate?: boolean;
    isFirstLevelCompleted?: boolean;
    isNotAvailable?: boolean;
    isVideoEmpty?: boolean;
    resumeId?: number;
}

