/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerOrderListModelDto } from './customerOrderListModelDto';


export interface CustomerOrderListModelDtoSchema { 
    customerOrderListModelDto?: CustomerOrderListModelDto;
    isSuccess?: boolean;
    message?: string | null;
}

