/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DecodedGuestTokenDto { 
    email?: string | null;
    userName?: string | null;
    userId?: string | null;
    jobId?: string | null;
    interviewId?: string | null;
    phone?: string | null;
    role?: string | null;
    meetingLink?: string | null;
    isSuccess?: boolean;
    message?: string | null;
}

