/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionUpdateModel } from './questionUpdateModel';


export interface DefaultQuestionsRequest { 
    questions?: Array<QuestionUpdateModel> | null;
}

