/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DesignationDto } from './designationDto';


export interface DesignationSchema { 
    designation?: DesignationDto;
    isSuccess?: boolean;
    message?: string | null;
}

