/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DesignationModel { 
    id?: number;
    sector?: string | null;
    department?: string | null;
    roleCategory?: string | null;
    designation?: string | null;
    keySkills?: string | null;
    designationStrength?: string | null;
}

