/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Download } from './download';


export interface DownloadListSchema { 
    downloadList?: Array<Download> | null;
    isSuccess?: boolean;
    message?: string | null;
}

