/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EarningHistoryModel } from './earningHistoryModel';


export interface EarningHistorySchema { 
    earningHistoryModel?: EarningHistoryModel;
    isSuccess?: boolean;
    message?: string | null;
}

