/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EducationalInformationDto } from './educationalInformationDto';


export interface EducationalInformationSchema { 
    educationalInformation?: EducationalInformationDto;
    isSuccess?: boolean;
    message?: string | null;
}

