/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExcelMappingDto } from './excelMappingDto';


export interface ExcelMappingSchema { 
    excelMappingDto?: ExcelMappingDto;
    isSuccess?: boolean;
    message?: string | null;
}

