/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExcelMapping { 
    id?: number;
    recruiterId?: number;
    fullName?: string | null;
    email?: string | null;
    mobileNumber?: string | null;
    currentCity?: string | null;
    workExperience?: string | null;
    currentJobTitle?: string | null;
    noticePeriod?: string | null;
    currentAnnualSalary?: string | null;
    companyName?: string | null;
    pgQualification?: string | null;
    pgSpecialization?: string | null;
    pgUniversity?: string | null;
    ugQualification?: string | null;
    ugSpecialization?: string | null;
    ugUniversity?: string | null;
    ugEndDate?: string | null;
    pgEndDate?: string | null;
    skills?: string | null;
    dateOfBirth?: string | null;
    gender?: string | null;
    profileSummary?: string | null;
    hometown?: string | null;
    workPermit?: string | null;
    pincode?: string | null;
    permanentAddress?: string | null;
    currentDepartment?: string | null;
    currentIndustry?: string | null;
    currentRoleCategory?: string | null;
    currentRoleJob?: string | null;
    preferredRole?: string | null;
    preferredCity?: string | null;
    expectedAnnualSalary?: string | null;
}

