/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilteredContractors { 
    id?: number;
    contractorUserId?: number;
    jobId?: number;
    designationId?: number;
    recruiterId?: number;
    recruiterHireAccept?: string | null;
    candidateAccepted?: string | null;
    candidateHireAccept?: string | null;
    userStatus?: string | null;
    recruiterStatus?: string | null;
    isClosed?: boolean;
    createdAt?: string;
    isCompleted?: boolean;
    completedAt?: string;
    updatedAt?: string;
    acceptedAt?: string;
    isHired?: boolean;
}

