/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinalResponseDto { 
    id?: number;
    userId?: number;
    supportAdminId?: number;
    jobId?: number;
    orderId?: number;
    reason?: string | null;
}

