/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinalResponseDto } from './finalResponseDto';


export interface FinalResponseSchema { 
    finalResponseDto?: FinalResponseDto;
    isSuccess?: boolean;
    message?: string | null;
}

