/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Folders } from './folders';


export interface FolderSchema { 
    folders?: Array<Folders> | null;
    isSuccess?: boolean;
    message?: string | null;
}

