/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UploadResume } from './uploadResume';
import { Tags } from './tags';


export interface FolderCandidate { 
    id?: number;
    userId?: number;
    fullName?: string | null;
    userName?: string | null;
    profileImage?: string | null;
    workExperience?: string | null;
    currentAnnualSalary?: string | null;
    noticePeriod?: string | null;
    expectedAnnualSalary?: string | null;
    jobTitle?: string | null;
    companyName?: string | null;
    currentCity?: string | null;
    isSaved?: boolean;
    qualification?: string | null;
    score?: number;
    rank?: number;
    totalExperienceMonths?: number;
    tags?: Array<Tags> | null;
    isResumeUpload?: boolean;
    isInterviewCompleted?: boolean;
    interviewStatus?: string | null;
    resumeId?: number;
    phoneNumber?: string | null;
    email?: string | null;
    isInterviewScheduled?: boolean;
    isVideoEmpty?: boolean;
    isSalaryConfidential?: boolean;
    years?: number;
    currentFolderId?: number;
    isPurchased?: boolean;
    uploadResume?: UploadResume;
    jobId?: number;
    isPrivate?: boolean;
    isRegister?: boolean;
    isDownloded?: boolean;
    isPrivateInterviewSchedule?: boolean;
    course?: string | null;
    specialization?: string | null;
    isPrimeRecruiter?: boolean;
    isTopCandidate?: boolean;
    isVerified?: boolean;
    isPrimeCandidate?: boolean;
    isPurchaseExpired?: boolean;
}

