/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { CommittedContract } from './committedContract';


export interface FreelancerContractorCardsPaginationSchema { 
    pagination?: Pagination;
    cardsList?: Array<CommittedContract> | null;
    isSuccess?: boolean;
    message?: string | null;
}

