/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { FreelancerEarningCandidatesforInterview } from './freelancerEarningCandidatesforInterview';


export interface FreelancerCandidatesCardsPaginationSchema { 
    pagination?: Pagination;
    cardsList?: Array<FreelancerEarningCandidatesforInterview> | null;
    isSuccess?: boolean;
    message?: string | null;
}

