/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FreelanceInterviewAccept { 
    id?: number;
    freelancerId?: number;
    userId?: number;
    interviewId?: number;
    productId?: number;
    recordingItemId?: string | null;
    candidateAccept?: string | null;
    scheduleTime?: string;
    scheduleEndTime?: string;
    meetingId?: string | null;
    interviewLink?: string | null;
    recordingPath?: string | null;
    recordingFetched?: boolean;
    transcriptFetched?: boolean;
    freelancerAmount?: number;
    interviewAmount?: number;
    transcriptPath?: string | null;
    transcriptText?: string | null;
}

