/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tags } from './tags';


export interface FreelanceCandidates { 
    userId?: number;
    fullName?: string | null;
    userName?: string | null;
    profileImage?: string | null;
    workExperience?: string | null;
    currentAnnualSalary?: string | null;
    noticePeriod?: string | null;
    expectedAnnualSalary?: string | null;
    jobTitle?: string | null;
    companyName?: string | null;
    currentCity?: string | null;
    isSaved?: boolean;
    tags?: Array<Tags> | null;
    resumeId?: number;
    resumeName?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    isSalaryConfidential?: boolean;
    resumePath?: string | null;
    matchPercentage?: number;
}

