/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FreelancerTitlesWithStatus } from './freelancerTitlesWithStatus';


export interface FreelancerAppliedCandidatesStatusSchema { 
    freelancerTitlesWithStatuses?: Array<FreelancerTitlesWithStatus> | null;
    isSuccess?: boolean;
    message?: string | null;
}

