/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FutureCustomerDto { 
    id?: number;
    name?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    resumeId?: number;
    uploadedBYId?: number;
}

