/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FutureCustomerDto } from './futureCustomerDto';


export interface FutureCustomerSchema { 
    futureCustomerDto?: FutureCustomerDto;
    isSuccess?: boolean;
    message?: string | null;
}

