/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GstModel { 
    id?: number;
    customerId?: number;
    advisorId?: number;
    gstNumber?: string | null;
    companyName?: string | null;
    companyAddress?: string | null;
}

