/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewProducts } from './interviewProducts';


export interface InterviewProductSchema { 
    interviewProduct?: InterviewProducts;
    isSuccess?: boolean;
    message?: string | null;
}

