/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleType } from './scheduleType';
import { InterviewStatus } from './interviewStatus';


export interface InterviewScheduleDto { 
    id?: number;
    userId?: number;
    scheduleDate?: string;
    scheduleTime?: string | null;
    status?: InterviewStatus;
    createdAt?: string;
    updatedAt?: string;
    feedbackId?: number;
    jobId?: number;
    recruiterId?: number;
    interviewRound?: number;
    candidateAccept?: string | null;
    scheduleTimeSlot?: string | null;
    interviewStatus?: string | null;
    scheduleType?: ScheduleType;
    productId?: number;
    keyskills?: string | null;
    isRetakeInterview?: boolean;
    isAcceptedDiscount?: boolean;
}
export namespace InterviewScheduleDto {
}


