/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewDto } from './interviewDto';


export interface InterViewSchema { 
    interviewDto?: InterviewDto;
    isSuccess?: boolean;
    message?: string | null;
}

