/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InterviewProducts { 
    productId?: number;
    productName?: string | null;
    price?: number;
    candidateCount?: number;
    totalPrice?: string | null;
    description?: string | null;
    subtitle?: string | null;
    subDescription?: string | null;
}

