/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewPackage } from './interviewPackage';


export interface InterviewPackageSchema { 
    interviewPackage?: InterviewPackage;
    redirectToMethod?: string | null;
    isSuccess?: boolean;
    message?: string | null;
}

