/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewSchedulesRangeDto } from './interviewSchedulesRangeDto';


export interface InterviewSchedulesRangeListSchema { 
    interviewSchedulesRangeDtos?: Array<InterviewSchedulesRangeDto> | null;
    isSuccess?: boolean;
    message?: string | null;
}

