/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewTimeSlotModel } from './interviewTimeSlotModel';


export interface InterviewTimeSlotListSchema { 
    slotName?: string | null;
    interviewTimeSlotModels?: Array<InterviewTimeSlotModel> | null;
}

