/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InterviewFeedback } from './interviewFeedback';


export interface InterviewFeedbackSchema { 
    interviewFeedbacks?: Array<InterviewFeedback> | null;
    overAllFeedback?: string | null;
    avgScore?: number;
    isSuccess?: boolean;
    message?: string | null;
}

