/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { CommentList } from './commentList';


export interface InterestCommentsSchema { 
    pagination?: Pagination;
    comments?: Array<CommentList> | null;
    isSuccess?: boolean;
    message?: string | null;
}

