/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const InterviewAvailabilityEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type InterviewAvailabilityEnum = typeof InterviewAvailabilityEnum[keyof typeof InterviewAvailabilityEnum];

