/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDetails { 
    languages?: Array<string> | null;
    requiredSkills?: Array<string> | null;
    favouriteKeySkills?: Array<string> | null;
    readonly additionalSkills?: Array<string> | null;
}

