/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobVacancy { 
    id?: number;
    jobTitle?: string | null;
    employmentType?: string | null;
    department?: string | null;
    experienceLevel?: string | null;
    workSchedule?: string | null;
    preferredGender?: string | null;
    preferredCities?: string | null;
    additionalDetails?: string | null;
    isRelocate?: boolean;
    exprienceStart?: number;
    exprienceEnd?: string | null;
    salaryRangeMin?: number;
    salaryRangeMax?: number;
    keySkills?: string | null;
    hideSalary?: boolean;
    companyIndustry?: string | null;
    featuredQualification?: string | null;
    candidateIndustry?: string | null;
    languageRequired?: string | null;
    conditions?: string | null;
    numberOfVacancies?: number | null;
    isWalkIn?: boolean;
    currency?: string | null;
    postingDate?: string;
    publishStatus?: boolean;
    isDeleted?: boolean;
    employerId?: number;
    noticePeriod?: string | null;
    companyId?: number | null;
    expiresOn?: string | null;
    updatedOn?: string | null;
    maxAllowedApplicants?: number | null;
    isClosed?: boolean;
    aiSkillKeywords?: string | null;
    jobPostType?: string | null;
    companyInfo?: string | null;
    link?: string | null;
    address?: string | null;
    jobDescription?: string | null;
    closedOn?: string | null;
    favouriteKeySkills?: string | null;
}

