/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LanguageDto { 
    id?: number;
    userId?: number;
    language?: string | null;
    proficiency?: string | null;
    comfortable?: Array<string> | null;
}

