/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultipleInterviewSchedulePopupResponse { 
    notFoundResumeIds?: Array<number> | null;
    alreadyGeneralInterviewscheduleIds?: Array<number> | null;
    notGeneralInterviewscheduleIds?: Array<number> | null;
    alreadyPrivateInterviewscheduleIds?: Array<number> | null;
    notPrivateInterviewscheduleIds?: Array<number> | null;
    alreadyGeneralInterviewCompletedIds?: Array<number> | null;
    notGeneralInterviewcompletedIds?: Array<number> | null;
    alreadyPrivateInterviewCompletedIds?: Array<number> | null;
    notPrivateInterviewCompletedIds?: Array<number> | null;
    alreadyPublicInterviewRequestedIds?: Array<number> | null;
    notPublicInterviewRequestedIds?: Array<number> | null;
    alreadyPrivateInterviewRequestedIds?: Array<number> | null;
    notPrivateInterviewRequestedIds?: Array<number> | null;
    alreadyInterviewScheduleIds?: Array<number> | null;
    notInterviewScheduleIds?: Array<number> | null;
    alreadyGeneralInterviewscheduleIdsCount?: number;
    notGeneralInterviewscheduleIdsCount?: number;
    alreadyPrivateInterviewscheduleIdsCount?: number;
    notPrivateInterviewscheduleIdsCount?: number;
    alreadyGeneralInterviewCompletedIdsCount?: number;
    notGeneralInterviewcompletedIdsCount?: number;
    alreadyPrivateInterviewCompletedIdsCount?: number;
    notPrivateInterviewCompletedIdsCount?: number;
    alreadyPublicInterviewRequestedIdsCount?: number;
    notPublicInterviewRequestedIdsCount?: number;
    alreadyPrivateInterviewRequestedIdsCount?: number;
    notPrivateInterviewRequestedIdsCount?: number;
    alreadyInterviewScheduleIdsCount?: number;
    notInterviewScheduleIdsCount?: number;
    isSuccess?: boolean;
    message?: string | null;
}

