/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MultiplePurchaseCandidates { 
    userId?: number;
    fullName?: string | null;
    userName?: string | null;
    profileImage?: string | null;
    workExperience?: string | null;
    currentAnnualSalary?: string | null;
    noticePeriod?: string | null;
    expectedAnnualSalary?: string | null;
    currentCity?: string | null;
    resumeId?: number;
    resumeName?: string | null;
    isSalaryConfidential?: boolean;
    resumePrice?: number;
    course?: string | null;
    specialization?: string | null;
}

