/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultipleResumeResponse } from './multipleResumeResponse';


export interface MultipleResumeResponseSchema { 
    multipleResumeResponse?: Array<MultipleResumeResponse> | null;
    failedUserIds?: Array<number> | null;
    isSuccess?: boolean;
    message?: string | null;
}

