/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface OrderReviewDataModelDto { 
    display?: boolean;
    billingAddress?: Address;
    isShippable?: boolean;
    shippingAddress?: Address;
    selectedPickupInStore?: boolean;
    pickupAddress?: Address;
    shippingMethod?: string | null;
    paymentMethod?: string | null;
    customValues?: { [key: string]: any; } | null;
}

