/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderNoteDto { 
    id?: number;
    hasDownload?: boolean;
    note?: string | null;
    createdOn?: string;
}

