/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetailsModelDto } from './orderDetailsModelDto';


export interface OrderDetailsModelDtoSchema { 
    orderDetailsModelDto?: OrderDetailsModelDto;
    isSuccess?: boolean;
    message?: string | null;
}

