/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { UserFollowingDto } from './userFollowingDto';
import { RecruiterFollowerDto } from './recruiterFollowerDto';


export interface PaginationFollowers { 
    pagination?: Pagination;
    followingDto?: Array<UserFollowingDto> | null;
    followerDto?: Array<RecruiterFollowerDto> | null;
}

