/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationPayment } from './paginationPayment';


export interface PaginationPaymentSchema { 
    paginationPayment?: PaginationPayment;
    isSuccess?: boolean;
    message?: string | null;
}

