/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentMethodDto { 
    id?: number;
    paymentMethodSystemName?: string | null;
    name?: string | null;
    description?: string | null;
    fee?: string | null;
    selected?: boolean;
    logoUrl?: string | null;
}

