/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Payment { 
    id?: number;
    paymentType?: number | null;
    paymentMode?: number | null;
    paymentGateway?: string | null;
    transactionId?: string | null;
    status?: boolean | null;
    message?: string | null;
    customerId?: number | null;
    subscriptionId?: number | null;
}

