/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentInstrumentDto { 
    type?: string | null;
    utr?: string | null;
    unmaskedAccountNumber?: string | null;
    cardType?: string | null;
    pgTransactionId?: string | null;
    bankTransactionId?: string | null;
    pgAuthorizationCode?: string | null;
    arn?: string | null;
    bankId?: string | null;
    brn?: string | null;
    pgServiceTransactionId?: string | null;
}

