/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentInstrumentDto } from './paymentInstrumentDto';


export interface PaymentDataDto { 
    merchantId?: string | null;
    merchantTransactionId?: string | null;
    transactionId?: string | null;
    date?: string;
    amount?: number;
    state?: string | null;
    responseCode?: string | null;
    responseCodeDescription?: string | null;
    paymentInstrument?: PaymentInstrumentDto;
}

