/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonalDetailsDto } from './personalDetailsDto';


export interface PersonalDetailsSchema { 
    personalDetails?: PersonalDetailsDto;
    isSuccess?: boolean;
    message?: string | null;
}

