/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostedJobsDto } from './postedJobsDto';


export interface PostedJobsSchema { 
    postedJobs?: Array<PostedJobsDto> | null;
    isSuccess?: boolean;
    message?: string | null;
}

