/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductItem { 
    name?: string | null;
    price?: string | null;
    total?: string | null;
    productAttributes?: Array<string> | null;
    mrp?: string | null;
    discount?: string | null;
    cgst?: string | null;
    sgst?: string | null;
}

