/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileModelDto } from './profileModelDto';


export interface ProfileModelDtoSchema { 
    profileModelDto?: ProfileModelDto;
    isSuccess?: boolean;
    message?: string | null;
}

