/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PurchaseResumeDto } from './purchaseResumeDto';


export interface PurchaseResumeSchemaDto { 
    purchaseResume?: PurchaseResumeDto;
    warnings?: Array<string> | null;
    redirectToMethod?: string | null;
    isSuccess?: boolean;
    message?: string | null;
}

