/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RazorPayStatusDataDto { 
    isPaymentSuccess?: boolean;
    razorPaySignature?: string | null;
    razorPayOrderId?: string | null;
    razorPayPaymentId?: string | null;
    reason?: string | null;
    code?: string | null;
    contact?: string | null;
    description?: string | null;
    step?: string | null;
    source?: string | null;
    email?: string | null;
}

