/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecruiterFolderDto } from './recruiterFolderDto';


export interface RecruiterFolderDtoSchema { 
    folders?: Array<RecruiterFolderDto> | null;
    isSuccess?: boolean;
    message?: string | null;
}

