/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecruiterFolderDto { 
    id?: number;
    folderName?: string | null;
    uploadedResumes?: number;
    userId?: number;
    createdAt?: string;
    isArchived?: boolean;
}

