/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecruiterInterviewScheduleRequest { 
    jobId?: number;
    orderId?: number;
    productId?: number;
    isAcceptedDiscount?: boolean;
    candidateIds?: Array<number> | null;
    skills?: Array<string> | null;
}

