/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferralCommissionDto } from './referralCommissionDto';


export interface ReferralCommissionResponse { 
    referralCommission?: ReferralCommissionDto;
    isSuccess?: boolean;
    message?: string | null;
}

