/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestLeaveDto { 
    id?: number;
    leaveType?: string | null;
    startDate?: string;
    endDate?: string;
    leaveReason?: string | null;
    userId?: number;
    jobId?: number;
    status?: string | null;
}

