/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { SavedCandidates } from './savedCandidates';


export interface SavedListCandidatesPaginationSchema { 
    pagination?: Pagination;
    savedCandidates?: Array<SavedCandidates> | null;
    isSuccess?: boolean;
    message?: string | null;
}

