/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SavedJobDto { 
    id?: number;
    recuiterId?: number;
    userId?: number;
    jobId?: number;
    savedAt?: string;
    savedType?: string | null;
    isSaved?: boolean;
}

