/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SelectAllCandidates { 
    userId?: number;
    resumeId?: number;
    isResumeUpload?: boolean;
    email?: string | null;
    isVideoEmpty?: boolean;
    isInterviewScheduled?: boolean;
    isInterviewCompleted?: boolean;
    interviewStatus?: string | null;
    isPrivate?: boolean;
    isPrivateInterviewSchedule?: boolean;
}

