/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SkillDto } from './skillDto';


export interface SkillSchema { 
    skillDto?: SkillDto;
    isSuccess?: boolean;
    message?: string | null;
}

