/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SkillQuestions } from './skillQuestions';
import { Tags } from './tags';


export interface SkillQuestionsSchema { 
    userId?: number;
    userName?: string | null;
    userProfile?: string | null;
    workExperienceYears?: number;
    workExperienceMonths?: number;
    noticePeriod?: string | null;
    expectedSalary?: string | null;
    skillQuestions?: Array<SkillQuestions> | null;
    questionSkillTags?: Array<Tags> | null;
    resumeId?: number;
    resumeName?: string | null;
    isPurchased?: boolean;
    isSavedCandidate?: boolean;
    course?: string | null;
    specialization?: string | null;
    isPrivate?: boolean;
    isVideoEmpty?: boolean;
    isSuccess?: boolean;
    message?: string | null;
}

