/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SkillScore { 
    id?: number;
    userId?: number;
    skill?: string | null;
    score?: number;
    level?: number;
    interviewId?: number;
    isLanguage?: boolean;
}

