/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SkillScore } from './skillScore';


export interface SkillScoreSchema { 
    skillScore?: Array<SkillScore> | null;
    overAllScore?: number;
    isSuccess?: boolean;
    message?: string | null;
}

