/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubAdminUsers { 
    id?: number;
    email?: string | null;
    isDeleted?: boolean;
    isApproved?: boolean;
    role?: string | null;
    recruiterId?: number;
    orderId?: number;
    isSuspended?: boolean;
    createdAt?: string;
}

