/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubAdminUsersDto } from './subAdminUsersDto';


export interface SubAdminUsersSchema { 
    subAdminUsersDto?: SubAdminUsersDto;
    isSuccess?: boolean;
    message?: string | null;
}

