/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubAdminValiditySchema } from './subAdminValiditySchema';


export interface SubAdminValidityListSchema { 
    subAdminValiditySchema?: Array<SubAdminValiditySchema> | null;
    isSuccess?: boolean;
    message?: string | null;
}

