/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupportAdminFilter { 
    keySkills?: string | null;
    industries?: string | null;
    department?: string | null;
    role?: string | null;
    interviewScheduledStatus?: string | null;
    minExperience?: number;
    maxExperience?: number;
    startDate?: string | null;
    endDate?: string | null;
    notRespond?: boolean;
    isIgnore?: boolean;
}

