/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSavedJobsListSchema } from './userSavedJobsListSchema';


export interface UserSavedJobsPagination { 
    userSavedobs?: UserSavedJobsListSchema;
    isSuccess?: boolean;
    message?: string | null;
}

