/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInterviewScheduleDto { 
    userId?: number;
    date?: string | null;
    time?: string | null;
    isInterviewDone?: boolean;
    interviewStatus?: string | null;
    interviewScheduleId?: number;
    retakeRequested?: boolean;
    retakeCompleted?: boolean;
}

