/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileScore { 
    userId?: number;
    score?: number;
    remainingScore?: number;
    isSuccess?: boolean;
    message?: string | null;
}

