/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleType } from './scheduleType';


export interface UserInterviewDetails { 
    jobId?: number;
    jobTitle?: string | null;
    companyName?: string | null;
    companyLogo?: string | null;
    name?: string | null;
    requestedOn?: string;
    scheduleType?: ScheduleType;
    date?: string | null;
    time?: string | null;
    candidateAccept?: string | null;
}
export namespace UserInterviewDetails {
}


