/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserSavedJobs { 
    id?: number;
    jobTitle?: string | null;
    companyName?: string | null;
    companyImage?: string | null;
    exprience?: string | null;
    field?: string | null;
    jobCount?: number | null;
    salaryRange?: string | null;
    location?: string | null;
    createdOn?: string;
    expiryOn?: string | null;
    keySkills?: Array<string> | null;
    requiredSkills?: Array<string> | null;
    isApplied?: boolean;
    likesCount?: number;
    commentsCount?: number;
    isCompanyFollow?: boolean;
    isSaved?: boolean;
    isLike?: boolean;
    jobStatus?: string | null;
    appliedCount?: number;
    companyId?: number;
    employerId?: number;
    hideSalary?: boolean;
    favouriteKeySkills?: Array<string> | null;
}

