/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VideoData { 
    videoId?: number;
    videoUrl?: string | null;
    answerScore?: number;
    questionId?: number;
    question?: string | null;
    questionScore?: number;
    likes?: number;
    isLiked?: boolean;
    isSaved?: boolean;
    commentsCount?: number;
    isVideoReady?: boolean;
}

