/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkExperienceDto { 
    id?: number;
    userId?: number;
    currentJobTitle?: string | null;
    companyName?: string | null;
    isCurrentCompany?: boolean;
    startDate?: string;
    endDate?: string | null;
    noticePeriod?: string | null;
    lastWorkingDay?: string | null;
    workplace?: string | null;
    employmentType?: string | null;
    currentAnnualSalary?: number | null;
    isSalaryConfidential?: boolean;
    description?: string | null;
}

