/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkTimeSheetModel } from './workTimeSheetModel';


export interface WorkTimeSheetDescriptionSchema { 
    contractJobId?: number;
    jobType?: string | null;
    title?: string | null;
    designation?: string | null;
    totalEarnings?: number;
    companyName?: string | null;
    location?: string | null;
    paidType?: string | null;
    workHours?: string | null;
    payment?: string | null;
    duration?: string | null;
    upcomingPayment?: string | null;
    updatedAt?: string;
    acceptedAt?: string;
    completedAt?: string;
    totalHours?: string | null;
    workedHoursThisWeek?: string | null;
    lastTimeSheetUpdatedAt?: string | null;
    workTimeSheetModels?: Array<WorkTimeSheetModel> | null;
    days?: Array<string> | null;
    totalCount?: number;
    isSuccess?: boolean;
    message?: string | null;
}

