/**
 * TrueValue
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkExperienceDto } from './workExperienceDto';


export interface WorkExperienceSchema { 
    workExperienceDto?: WorkExperienceDto;
    isSuccess?: boolean;
    message?: string | null;
}

